feat: Initial frontend implementation
g3vxy/mnb_ml pull request #1
Opened 2021-01-06 21:05 UTC by Anlerkan

### Description

- **Initial frontend implementation :tada:**

2021-01-06 21:49 UTC, Anlerkan commented on frontend/config/apiConfig.json
> +
Unnecessary for now.

2021-01-06 21:49 UTC, Anlerkan commented on frontend/public/index.html
> +    <title>React App</title>
- Change title and description

2021-01-06 21:53 UTC, Anlerkan commented on frontend/src/home/page/form/PredictSentenceForm.tsx
> +      {result.result === false && <Result result={result} />}
`{result.result ? <Result result={result}/> }`

2021-01-06 22:25 UTC, Anlerkan commented on frontend/src/core/root-app/RootApp.tsx
> +    </BrowserRouter>
Use `<HashRouter>` instead of BrowserRouter

2021-01-07 06:56 UTC, g3vxy requested changes
frontend/.env shouldn't be in the repo @Anlerkan. Apart from that it seems good.

2021-01-08 16:14 UTC, merged